[build]
  command = """
    gem install bundler -v '2.0.2'
    pip install -U git+https://github.com/UBC-MDS/PPDS_book
    jupyter-book create PPDS_book --content-folder content
    cd PPDS_book
    jupyter-book build ./ --overwrite
    make install
    bundle exec jekyll build
    """

  publish = "PPDS_book/_site"
